#!/bin/bash
if [[ "$#" -ne 3 ]]; then
echo "Usage: rgb file width contraststretch"
exit 1
fi
if [ ! -d "../rendered" ]; then
mkdir ../rendered
fi
mkdir temp
convert "$1" -contrast-stretch "$3"%x0% -resize "$2"x temp/temp.png
convert temp/temp.png -resize "100%x52%" temp/temp2.png
WIDTH=`identify -format "%w" temp/temp2.png`
HEIGHT=`identify -format "%h" temp/temp2.png`
echo -n 'RGBA' > ../rendered/"$1".rgba
printf "0: %.2x" "$WIDTH" | xxd -r -g0 >> ../rendered/"$1".rgba
printf "0: %.2x" "$HEIGHT" | xxd -r -g0 >> ../rendered/"$1".rgba
convert temp/temp2.png -depth 8 temp/temp.rgba
cat temp/temp.rgba >> ../rendered/"$1".rgba
rm -rf temp
echo $WIDTH
echo $HEIGHT
